plugins:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  flog:
    enabled: true
  editorconfig:
    enabled: true
  brakeman:
    enabled: true
  reek:
    enabled: true