version: "3"

# SPECIAL NOTES:
# 1.  GEM_HOME is set to the tmp/gem_home directory in this app.
#     Bundler is installed here.
#     If you delete Bundler from this directory, you will get an error
#     message about not having the correct version of bundler when you
#     run "bundle install" or try to do just about anything else.
# 2.  BUNDLE_PATH is set to the tmp/bundle directory in this app.
#     The products of "bundle install" are saved here.  If you delete
#     this directory, subsequent executions of the "bundle install"
#     process will take longer.

services:
  rails:
    build: .
    volumes:
      - .:/home/winner/myapp
    environment:
      - BUNDLE_PATH=/home/winner/myapp/tmp/bundle
      - BUNDLE_APP_CONFIG=/home/winner/myapp/.bundle
      - GEM_HOME=/home/winner/myapp/tmp/gem_home
    user: winner
    command:
      - bundle
      - exec
      - rails
      - server
      - --binding=0.0.0.0
      - --port=3000
    ports:
      - "3001:3000"
    links:
      - mailcatcher
    env_file:
      - .docker-env/development/database
    depends_on:
      - database

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

  database:
    image: postgres
    env_file:
      - .docker-env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"

volumes:
  db_data:
