name: CI
on: [push, pull_request]
jobs:
  lint_backend:
    name: Backend linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Rubocop
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
  lint_frontend:
    name: Frontend linting
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Go to Client App
        run: cd client
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --watchAll=false
  test_backend:
    name: Backend tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec rails db:prepare
          bundle exec rspec
  test_frontend:
    name: Frontend tests
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Go to Client App
        run: cd client
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --watchAll=false